SELECT
  PRODUCT_CODE,
  SUM(COALESCE(SALES_AMOUNT, 0)) * PRICE AS SALES
FROM PRODUCT
LEFT JOIN OFFLINE_SALE
ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT_CODE, PRICE
ORDER BY SALES DESC, PRODUCT_CODE