SELECT
 ANIMAL_ID,
 ANIMAL_TYPE,
 NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS USING(ANIMAL_ID,ANIMAL_TYPE,NAME)
WHERE ANIMAL_INS.SEX_UPON_INTAKE LIKE "%INtact%" AND ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE "%INtact%"