SELECT
 ANIMAL_ID,
 ANIMAL_TYPE,
 NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS USING(ANIMAL_ID,ANIMAL_TYPE,NAME)
WHERE (ANIMAL_INS.SEX_UPON_INTAKE = 'Intact Female' AND ANIMAL_OUTS.SEX_UPON_OUTCOME = 'Spayed Female') OR (ANIMAL_INS.SEX_UPON_INTAKE = 'Intact Male' AND ANIMAL_OUTS.SEX_UPON_OUTCOME = 'Neutered Male')