SELECT YEAR(SALES_DATE) AS YEAR , MONTH(SALES_DATE) AS MONTH , COUNT(DISTINCT CASE WHEN  USER_ID IN (SELECT  USER_ID FROM USER_INFO WHERE YEAR(JOINED)=2021) THEN USER_ID END) AS PURCHASED_USERS ,ROUND(COUNT(DISTINCT CASE WHEN USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED)=2021) THEN USER_ID END)/(SELECT COUNT (USER_ID)
FROM USER_INFO
WHERE YEAR(JOINED)=2021),1) PUCHASED_RATIO
FROM ONLINE_SALE
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1,2