SELECT
 APNT_NO,PT_NAME,PT_NO,AP.MCDP_CD,DR_NAME,APNT_YMD
FROM (SELECT
 APNT_NO,PT_NO,MCDP_CD,APNT_YMD,MDDR_ID
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD,"%Y-%m-%d") = "2022-04-13" AND APNT_CNCL_YN = 'N' AND MCDP_CD = "CS"
) AS AP
JOIN DOCTOR ON AP.MDDR_ID = DOCTOR.DR_ID
JOIN PATIENT USING(PT_NO)
ORDER BY APNT_YMD