SELECT USR.USER_ID USER_ID , USR.NICKNAME NICKNAME , SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER USR ON (B.WRITER_ID = USR.USER_ID)
WHERE B.STATUS = "DONE"
GROUP BY USR.USER_ID
HAVING SUM(B.PRICE) >=700000
ORDER BY 3 