SELECT
 ICECREAM_INFO.FLAVOR
FROM(SELECT 
 FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER>3000
ORDER BY TOTAL_ORDER DESC) AS HALF
LEFT JOIN ICECREAM_INFO
ON ICECREAM_INFO.FLAVOR = HALF.FLAVOR
WHERE INGREDIENT_TYPE = "fruit_based"