SELECT
 TITLE,
 GOODS.BOARD_ID,
 REPLY_ID,
 REPLY.WRITER_ID,
 REPLY.CONTENTS,
 DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS REPLY
LEFT JOIN USED_GOODS_BOARD AS GOODS
ON GOODS.BOARD_ID = REPLY.BOARD_ID
WHERE (GOODS.CREATED_DATE BETWEEN 20221001 AND 20221031 )
ORDER BY REPLY.CREATED_DATE, TITLE

