WITH A AS (SELECT
CATEGORY,
MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY in ("과자","국","김치","식용유")
GROUP BY CATEGORY)

SELECT
CATEGORY,
MAX_PRICE,
PRODUCT_NAME
FROM FOOD_PRODUCT JOIN A USING(CATEGORY)
WHERE MAX_PRICE = PRICE
ORDER BY MAX_PRICE DESC