SELECT
 B.BOOK_ID,
 AUTHOR.AUTHOR_NAME,
 DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM(SELECT
 BOOK_ID,
 AUTHOR_ID,
 PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY="경제"
) AS B
LEFT JOIN AUTHOR
ON B.AUTHOR_ID=AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE